### ISSUE TITLE
test: add comprehensive test suite for ecosystem-manager.sh

### ISSUE THREAD

**Issue by toshi0806** [smkwlab/latex-ecosystem#15]
## 概要
ecosystem-manager.shの品質向上と回帰防止のため、包括的なテストスイートを追加します。

### 1. 基本機能テスト
```bash
# tests/basic_functionality.bats
test_status_command_basic() {
    run ./ecosystem-manager.sh status
    [ "$status" -eq 0 ]
    [[ "$output" =~ "Repository Status Overview" ]]
}

test_help_command() {
    run ./ecosystem-manager.sh help
    [ "$status" -eq 0 ]
    [[ "$output" =~ "Usage:" ]]
}
```

### 2. GitHub統合テスト
```bash
# tests/github_integration.bats
test_pr_status_without_gh() {
    # GitHub CLIが利用できない環境での動作
    PATH="/usr/bin:/bin" run ./ecosystem-manager.sh status
    [ "$status" -eq 0 ]
    # エラーで停止せず、PRカラムが"-"または"0"で表示される
}

test_pr_filtering() {
    run ./ecosystem-manager.sh status --with-prs
    [ "$status" -eq 0 ]
    [[ "$output" =~ "Open Pull Requests" ]]
}
```

### 3. 表示フォーマットテスト
```bash
# tests/display_format.bats
test_compact_mode_column_alignment() {
    run ./ecosystem-manager.sh status
    # 固定幅カラムの確認
    lines=("${output[@]}")
    # ヘッダー行の確認
    [[ "${lines[2]}" =~ ^[[:space:]]*Repository[[:space:]]+Branch ]]
}

test_long_mode_full_names() {
    run ./ecosystem-manager.sh status --long
    # 省略されていない完全名の確認
    [[ "$output" =~ $'\t' ]]  # タブ区切りの確認
}
```

### 4. エッジケーステスト
```bash
# tests/edge_cases.bats
test_very_long_repository_names() {
    # 非常に長いリポジトリ名での表示テスト
    local long_name="very-very-very-very-long-repository-name-that-exceeds-normal-limits"
    # モックリポジトリでのテスト
}

test_special_characters_in_names() {
    # 特殊文字を含むブランチ名でのテスト
    # 日本語文字でのテスト
}

test_network_failure_simulation() {
    # ネットワーク不通時のGitHub API呼び出し失敗テスト
}
```

### 5. パフォーマンステスト
```bash
# tests/performance.bats
test_multiple_repositories_performance() {
    # 10+リポジトリでの実行時間測定
    start_time=$(date +%s)
    run ./ecosystem-manager.sh status
    end_time=$(date +%s)
    
    execution_time=$((end_time - start_time))
    # 合理的な実行時間（例：30秒以内）の確認
    [ "$execution_time" -lt 30 ]
}
```

### 6. モック/フィクスチャの設定
```bash
# tests/setup_mock_repos.sh
setup_test_environment() {
    # テスト用の模擬リポジトリディレクトリ構造作成
    # モックのGitHub API レスポンス設定
    # テストデータの初期化
}
```

### Bats (Bash Automated Testing System)
```bash
# インストール
git submodule add https://github.com/bats-core/bats-core.git tests/bats
```

### CI/CD統合
```yaml
# .github/workflows/test.yml
name: Test ecosystem-manager
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Run tests
        run: tests/bats/bin/bats tests/
```

## 実装計画
1. **Phase 1**: 基本機能テストの実装
2. **Phase 2**: GitHub統合テストの追加
3. **Phase 3**: エッジケースとパフォーマンステスト
4. **Phase 4**: CI/CD統合

## 成功基準
- [ ] テストカバレッジ80%以上
- [ ] 全てのコマンドラインオプションのテスト
- [ ] エラー条件での適切な動作確認
- [ ] CI/CDでの自動実行

## 優先度
High - 品質保証と今後の開発効率のため重要

## 関連
- PR #11 - GitHub PR integration (Phase 2)
- Issue #12 - Performance optimization
- Issue #13 - Error handling improvements
