### ISSUE TITLE
Improve latex-template workflows

### ISSUE THREAD

**Issue by toshi0806** [smkwlab/latex-ecosystem#2]
# Improve latex-template workflows

## 現状分析

latex-templateの学生用ワークフローは、sotsuron-templateと比較して機能が不足しており、学生の利便性向上が必要です。

### 現在のlatex-template
- ✅ 基本的なPDF生成（単一ファイル）
- ✅ PRでのアーティファクトアップロード
- ❌ ワークフロー管理なし
- ❌ 複数ファイル対応なし
- ❌ 進捗管理なし

### sotsuron-templateの充実した機能（参考）
- ✅ 複数文書同時生成（本文・概要・スライド等）
- ✅ 段階的執筆支援（draft-1st, 2nd, 3rd...）
- ✅ 自動レビューシステム
- ✅ 最終提出自動化
- ✅ 教員向け添削支援

#### 1. 複数ファイル対応のlatex-build.yml
```yaml
- uses: smkwlab/latex-release-action@v2.2.0
  with:
    files: main, appendix, slide, report
    upload_on_pr: true
```
**効果**: レポート、スライド、付録を同時生成。学会発表等の複数文書ニーズに対応。

#### 2. ワークフローにコメント・ドキュメント追加
- 各ステップの説明コメント追加
- パラメータの用途明確化
- 学生向け使用方法ガイド

#### 3. check-texlive-updates.yml追加
- 依存関係の自動更新チェック
- 最新LaTeX環境の維持

#### 4. 段階的執筆支援（create-next-version.yml）
```yaml
name: Create Next Version
on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type'
        required: true
        default: 'version'
        type: choice
        options:
        - version
        - draft
        - final
```
**機能**:
- `version-1`, `version-2`等の連番ブランチ自動作成
- PR作成時の次ステップ案内
- 進捗管理支援

#### 5. 設定可能なワークフロー
```yaml
# .github/config.yml
features:
  multi_document: true      # 複数文書生成
  version_management: true  # バージョン管理
  review_system: false     # レビュー機能（デフォルト無効）
  quality_check: true      # 品質チェック
```

#### 6. 自動品質チェック機能
- LaTeX構文エラーの分かりやすい説明
- 図表参照の整合性確認
- 基本的な文書構造検証
- 初回利用者向けガイダンス

#### 7. 軽量レビューシステム（オプション）
- 教員指導がある場合のみ有効化
- sotsuron-templateより簡素化された版
- review-branchの自動管理

#### 8. 自動提出システム（評価対象文書用）
```yaml
name: Auto Final Release
on:
  push:
    tags:
      - 'final-*'
```

### 汎用性重視
- 論文特化ではなく、レポート・卒業研究・学会発表等に幅広く対応
- 学習コスト配慮：基本機能から段階的に高度機能を追加

### 柔軟な機能選択
- 設定ファイルで機能のON/OFF切替
- 用途に応じたカスタマイズ性

### 学生体験向上
- **複数形式出力**: PDF、スライド、ハンドアウトの同時生成
- **自動バックアップ**: 重要節目での自動バージョン保存
- **進捗可視化**: 現在の執筆段階の明確な表示
- **テンプレート選択**: 用途別初期設定（レポート用、論文用、スライド用）

## 実装優先度

**高優先度（即座に）**:
1. 複数ファイル対応latex-build.yml
2. ワークフローコメント・ドキュメント追加
3. check-texlive-updates.yml追加

**中優先度（短期）**:
4. 段階的執筆支援機能
5. 設定可能なワークフロー
6. 自動品質チェック

**低優先度（長期・条件付き）**:
7. 軽量レビューシステム
8. 自動提出システム

## 期待される効果

この改善により、latex-templateは「学習しやすく、成長に合わせて高機能化できる汎用LaTeXテンプレート」として、sotsuron-templateとは異なる価値を提供し、学生の LaTeX 学習と文書作成を大幅に支援できます。

## 関連

- Phase 2の改善はlatex-ecosystem#1のロードマップとも連携
- sotsuron-templateの成功要素を汎用的に応用
