### ISSUE TITLE
Add automated test suite for ecosystem-manager.sh

### ISSUE THREAD

**Issue by toshi0806** [smkwlab/latex-ecosystem#24]
## 概要
ecosystem-manager.sh の品質保証とリグレッション防止のため、包括的な自動テストスイートを実装します。

## 背景
現在、ecosystem-manager.sh は1,180行、37関数の大規模なBashスクリプトですが、自動テストが存在しません。手動テストに依存しており、変更時のリグレッションリスクが高い状態です。

### 1. 単体テスト (Unit Tests)
**対象関数の例**
```bash
# ユーティリティ関数
- truncate_string()
- safe_jq()
- is_cache_valid()
- get_repo_display_name()

# 認証/検証関数
- check_github_cli()
- repo_exists()
- check_environment()
```

**テスト例**
```bash
test_truncate_string() {
    # 通常ケース
    assert_equals "$(truncate_string "hello world" 5)" "he..."
    
    # マルチバイト文字
    assert_equals "$(truncate_string "こんにちは世界" 5)" "こん..."
    
    # 短い文字列
    assert_equals "$(truncate_string "hi" 5)" "hi"
}
```

### 2. 統合テスト (Integration Tests)
**テストシナリオ**
- キャッシュ機能の動作確認
- GitHub API呼び出しのモック
- 複数リポジトリでの動作確認
- エラーハンドリングの検証

**テスト例**
```bash
test_cache_functionality() {
    # キャッシュクリア
    ./ecosystem-manager.sh --clear-cache
    
    # 初回実行（APIコール）
    output1=$(./ecosystem-manager.sh status --repo test-repo)
    
    # 2回目実行（キャッシュ使用）
    output2=$(./ecosystem-manager.sh status --repo test-repo)
    
    assert_equals "$output1" "$output2"
}
```

### 3. エンドツーエンドテスト (E2E Tests)
**実際のコマンド実行**
```bash
test_status_command() {
    # 全リポジトリステータス
    ./ecosystem-manager.sh status
    assert_exit_code 0
    
    # フィルタリングオプション
    ./ecosystem-manager.sh status --urgent-issues
    ./ecosystem-manager.sh status --with-prs
    ./ecosystem-manager.sh status --needs-review
}
```

### 4. パフォーマンステスト
**測定項目**
- キャッシュなし実行時間
- キャッシュあり実行時間
- 並列処理の効果測定

### 推奨: bats (Bash Automated Testing System)
```bash
# インストール
npm install -g bats

# テスト実行例
#\!/usr/bin/env bats

@test "check_github_cli returns success when authenticated" {
    # モック設定
    function gh() { echo "Active account: true"; return 0; }
    export -f gh
    
    run check_github_cli
    [ "$status" -eq 0 ]
}
```

### 代替案: 純粋Bashテストフレームワーク
```bash
# tests/test_framework.sh
assert_equals() {
    if [ "$1" \!= "$2" ]; then
        echo "FAIL: Expected '$2' but got '$1'"
        return 1
    fi
}

assert_exit_code() {
    if [ $? -ne "$1" ]; then
        echo "FAIL: Expected exit code $1"
        return 1
    fi
}
```

### GitHub Actions設定
```yaml
name: Test ecosystem-manager

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq shellcheck
          npm install -g bats
      
      - name: Run shellcheck
        run: shellcheck ecosystem-manager.sh
      
      - name: Run unit tests
        run: bats tests/unit/
      
      - name: Run integration tests
        run: bats tests/integration/
```

### GitHub CLIモック
```bash
# tests/mocks/gh_mock.sh
mock_gh_auth_status() {
    echo "Active account: true"
    return 0
}

mock_gh_issue_list() {
    echo '[{"number":1,"title":"Test issue"}]'
}
```

### 品質向上
- リグレッションの早期発見
- エッジケースのカバー
- 信頼性の向上

### 開発効率
- 安全なリファクタリング
- 迅速なフィードバック
- ドキュメントとしての役割

### 保守性
- 変更の影響範囲の明確化
- 新機能追加時の既存機能保証
- コントリビューターへの安心感

### Phase 1: テスト基盤構築 (1週間)
- テストフレームワーク選定
- ディレクトリ構造設計
- CI/CD設定

### Phase 2: 単体テスト実装 (2週間)
- ユーティリティ関数のテスト
- 主要関数のテスト
- カバレッジ目標: 70%

### Phase 3: 統合・E2Eテスト (1週間)
- 主要シナリオのテスト
- エラーケースのテスト
- パフォーマンステスト

## 成功指標
- テストカバレッジ: 80%以上
- 全てのPRでテスト実行必須
- テスト実行時間: 5分以内

## 優先度
高 - 大規模スクリプトの品質保証には自動テストが不可欠

## 関連
- Issue #23 - Shellcheck warnings fix
- Issue #15 - Original test suite request
