### ISSUE TITLE
学生リポジトリ作成から管理までの完全自動化ワークフロー実装

### ISSUE THREAD

**Issue by toshi0806** [smkwlab/latex-ecosystem#29]
# 🎓 学生リポジトリ作成から管理までの完全自動化ワークフロー実装

## 📋 **課題**

現在のthesis-management-toolsでは以下の課題があります：

1. **bulk-setup-protection.shが実用的でない**
   - 学生がIssueを作成しても手動実行が必要
   - pending-protection.txtの手動管理

2. **thesis-repo-manager.sh statusが重い**
   - 毎回GitHub APIで全リポジトリを取得
   - 年度別・タイプ別の絞り込みが困難

3. **学生リポジトリの管理が困難**
   - 卒業生と現役生のリポジトリが混在
   - 学部生・大学院生の区別が難しい

### **アーキテクチャ概要**

```
学生のsetup.sh実行
        ↓
   Issue自動作成
        ↓
GitHub Actions (2時間ごと)
        ↓
Issue駆動でブランチ保護設定
        ↓
学生レジストリ自動更新
        ↓
thesis-repo-manager.sh高速化
```

### **管理ファイル構造**

```
data/
├── students/
│   ├── current-year.txt         # "2024"
│   ├── 2021/
│   │   ├── undergraduate.txt    # k21rs001, k21rs002, k21rs003
│   │   └── graduate.txt         # k21gjk01
│   ├── 2022/
│   │   ├── undergraduate.txt    
│   │   └── graduate.txt         
│   └── 2024/
│       ├── undergraduate.txt    
│       └── graduate.txt         
├── protection-status/
│   ├── pending-protection.txt   # ブランチ保護待ち
│   ├── completed-protection.txt # ブランチ保護完了
│   └── failed-protection.txt    # ブランチ保護失敗
└── repositories/
    ├── active.txt              # アクティブリポジトリ一覧
    └── archived.txt            # アーカイブ済みリポジトリ
```

### **setup.sh実行フロー**
```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/smkwlab/thesis-management-tools/main/create-repo/setup.sh)"

# 処理内容:
# 1. Docker環境でmain.sh実行
# 2. テンプレートからリポジトリ作成
# 3. 学生IDに応じたファイル整理
# 4. LaTeX環境セットアップ（aldc quiet mode）
# 5. ブランチ構成作成（initial, review-branch, 0th-draft）
# 6. ブランチ保護設定依頼Issue自動作成 ← 新機能
```

### **Issue自動作成内容例**
```
タイトル: ブランチ保護設定依頼: k21rs001-sotsuron
本文:
学籍番号: k21rs001
リポジトリ: smkwlab/k21rs001-sotsuron
学生タイプ: 学部生 (卒業論文)
作成日時: 2024-06-21T16:30:00Z

自動ブランチ保護設定をリクエストします。
```

### **GitHub Actions定期実行**
```yaml
# .github/workflows/student-repo-management.yml
name: Student Repository Management
on:
  schedule:
    - cron: '0 */2 * * *'  # 2時間ごと
  workflow_dispatch: # 手動実行も可能

jobs:
  manage-repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Extract student info from issues
        run: ./scripts/extract-student-info-from-issues.sh
      
      - name: Setup branch protection  
        run: ./scripts/bulk-setup-protection.sh
        
      - name: Update student registry
        run: ./scripts/update-student-registry.sh
        
      - name: Commit registry updates
        run: |
          git add data/
          git commit -m "Update student registry and protection status"
          git push
```

### **処理フロー**

1. **Issue駆動学生情報抽出**
   ```bash
   # 未処理Issueから学生情報を抽出・分類
   gh issue list --label "ブランチ保護設定" --state open
   # 学籍番号から年度・タイプを判定
   # data/students/{year}/{type}.txt に記録
   ```

2. **ブランチ保護設定実行**
   ```bash
   # pending-protection.txtから自動実行
   # 成功→completed-protection.txtに移動
   # 失敗→failed-protection.txtに記録
   ```

3. **Issue自動クローズ**
   ```bash
   # 処理完了したIssueに完了コメント追加
   # "✅ ブランチ保護設定が自動実行されました"
   # Issue自動クローズ
   ```

### **拡張されたthesis-repo-manager.sh**

```bash
# 年度別状況確認（高速）
./thesis-repo-manager.sh status 2024
📊 2024年度 学生リポジトリ状況
================================
🎓 学部生 (15名):
  k24rs001 ✅ ブランチ保護済み
  k24rs002 ⏳ ブランチ保護待ち
  k24rs003 ✅ ブランチ保護済み
  ...

🎓 大学院生 (3名):
  k24gjk01 ✅ ブランチ保護済み
  k24gjk02 ✅ ブランチ保護済み
  k24gjk03 ❌ ブランチ保護失敗

# タイプ別確認
./thesis-repo-manager.sh status 2024 undergraduate

# 全体概要
./thesis-repo-manager.sh status
📊 全体状況
==========
🔒 ブランチ保護完了: 156
⏳ ブランチ保護待ち: 3
❌ ブランチ保護失敗: 1
📝 アクティブリポジトリ: 160
```

### **完全自動化**
- ✅ 学生: setup.sh実行のみ
- ✅ システム: Issue→ブランチ保護→レジストリ更新を自動実行
- ✅ 教員: 必要時にstatus確認のみ

### **高速化**
- ✅ APIではなくローカルファイルから高速取得
- ✅ 年度・タイプでの絞り込み可能
- ✅ 大量のリポジトリでもスケーラブル

### **年度別管理**
- ✅ 学生IDから年度を自動抽出（k21rs001 → 2021年度）
- ✅ 学部生・大学院生を自動分類
- ✅ 過去の学生データも保持

### **トレーサビリティ**
- ✅ Issue→ブランチ保護→レジストリ更新の全工程を記録
- ✅ GitHubのActionsログで実行履歴確認可能
- ✅ 失敗時の原因追跡も容易

### **Phase 1: Issue駆動システム**
- [ ] extract-student-info-from-issues.sh 作成
- [ ] GitHub Actions workflow作成
- [ ] main.shにIssue作成機能追加

### **Phase 2: 学生レジストリシステム**
- [ ] data/ディレクトリ構造作成
- [ ] update-student-registry.sh 作成
- [ ] bulk-setup-protection.sh拡張

### **Phase 3: thesis-repo-manager.sh拡張**
- [ ] 年度別status確認機能
- [ ] 高速化（ファイルベース取得）
- [ ] レジストリ管理コマンド追加

### **Phase 4: 統合テスト**
- [ ] end-to-endテストシナリオ作成
- [ ] 既存データのマイグレーション
- [ ] ドキュメント更新

### **学生ID解析ロジック**
```bash
# k21rs001 → 2021年度学部生
# k21gjk01 → 2021年度大学院生
parse_student_id() {
    local student_id="$1"
    local year="20$(echo "$student_id" | grep -oE '[0-9]{2}' | head -1)"
    local type=""
    
    if echo "$student_id" | grep -q 'rs'; then
        type="undergraduate"
    elif echo "$student_id" | grep -q 'gjk'; then
        type="graduate"  
    fi
    
    echo "$year $type"
}
```

### **レジストリファイル形式**
```bash
# data/students/2024/undergraduate.txt
k24rs001
k24rs002
k24rs003

# data/protection-status/completed-protection.txt  
k24rs001-sotsuron
k24rs002-sotsuron
k24gjk01-sotsuron
```

## 🚀 **次のステップ**

1. **Phase 1から順次実装**
2. **小規模テストでの動作確認**
3. **既存システムとの統合**
4. **本格運用開始**

この実装により、学生リポジトリの作成から管理まで完全に自動化され、教員の負担を大幅に軽減できます。

## 📞 **実装支援**

この提案について詳細検討や実装支援が必要でしたら、お声かけください。段階的な実装計画や技術的な詳細についても対応可能です。
